party:
  isSetup: false
lobby:
  pos1:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0.0
    yaw: 0.0
  pos2:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0.0
    yaw: 0.0
  spawn:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 90