name: MiniRoyal
version: '${project.version}'
main: fr.zuhowks.miniroyal.MiniRoyal
load: POSTWORLD

commands:
  amr:
    description: Admin commands for Mini-Royal
    usage: /amr
    permission: miniroyal.admin
  miniroyal:
    description: Commands for Mini-Royal
    usage: /miniroyal

permissions:
  miniroyal.admin:
    default: op
    description: admin permission